### ISSUE TITLE
Unable to get working on 10.15 - was previously working on 10.14

### ISSUE THREAD

**Issue by dgwilson** [chuckhoupt/jekyll-apple-help#23]
Ruby version check:
ruby -v
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

I've reinstalled jekyll from the command line.
sudo gem install bundler jekyll

I've had to edit the run script  
cd "$PROJECT_DIR/$EXECUTABLE_NAME"
pwd
/usr/bin/make --always-make

Now the Makefile is found.

Current build errors are as follows:

------------------------------------------------------------------------------------------------------------------
Showing Recent Messages
[[ -s "/Users/dgwilson/.rvm/environments/default" ]] && source "/Users/dgwilson/.rvm/environments/default" ; \

	(which -s jekyll || (echo "error: Jekyll not found - check setup requirements" ; false )) \

	&& jekyll build --destination "/Users/dgwilson/Library/Developer/Xcode/DerivedData/Moments-blbepuscugzjooezmsylluyfhlfh/Build/Products/Debug/MomentsHelp.help/Contents/Resources"

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle, 0x0009): dependent dylib '/usr/local/opt/libffi/lib/libffi.6.dylib' not found for '/Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle' - /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi_c.bundle (LoadError)

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:6:in `rescue in <top (required)>'

	from /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:3:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Users/dgwilson/.gem/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Users/dgwilson/.gem/ruby/2.6.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'

	from /usr/local/bin/jekyll:23:in `load'

	from /usr/local/bin/jekyll:23:in `<main>'

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- 2.6/ffi_c (LoadError)

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/ffi-1.13.1/lib/ffi.rb:4:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc/native.rb:3:in `<top (required)>'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `require_relative'

	from /Library/Ruby/Gems/2.6.0/gems/sassc-2.4.0/lib/sassc.rb:31:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:3:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Library/Ruby/Gems/2.6.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll-sass-converter.rb:4:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Users/dgwilson/.gem/ruby/2.6.0/gems/jekyll-4.1.1/lib/jekyll.rb:209:in `<top (required)>'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'

	from /Users/dgwilson/.gem/ruby/2.6.0/gems/jekyll-4.1.1/exe/jekyll:8:in `<top (required)>'

	from /usr/local/bin/jekyll:23:in `load'

	from /usr/local/bin/jekyll:23:in `<main>'

------------------------------------------------------

Also did this... and it hasn't altered the build error.

sudo gem install ffi --platform=ruby
Password:
Building native extensions. This could take a while...
Successfully installed ffi-1.13.1
Parsing documentation for ffi-1.13.1
Done installing documentation for ffi after 2 seconds
1 gem installed

I don't know what to do next. Any one have any idea?

- David

**Comment by chucker** [comment]
You probably want to not use Apple's Ruby toolchain. It's a bit old and also limited in terms of permissions.

I ultimately went with this guide: http://jekyllrb.com/docs/installation/macos/

**Comment by arqbackup** [comment]
-- Please reply above this line --


Hello,

We received your email. We'll get back to you as soon as possible. We
strive to answer emails within 1 business day.

Arq Backup
***@***.***
